### ISSUE TITLE
New Online Course: CSS to Sass: Converting an Existing Site

### ISSUE THREAD

**Issue by JohnRiv** [sushiandrobots/sassnews.com#1]
Thanks for stepping up and taking over Sass News! 

My first Lynda.com course was just published last week, and I believe it's particularly relevant to the readers of Sass News:

CSS to Sass: Converting an Existing Site
http://www.lynda.com/CSS-tutorials/CSS-Sass-Converting-Existing-Site/434463-2.html

As the title says, it helps developers through the process of converting a website from using vanilla CSS to using Sass. It also goes into details of using node-sass, Autoprefixer, Eyeglass, and Eyeglass-Spriting, so even developers already using Sass may find those videos useful if they're not already using those tools.

**Comment by jina** [comment]
Will be in the next issue going out tonight. Thanks!
