### ISSUE TITLE
Sassy-Gridlover

### ISSUE THREAD

**Issue by hiulit** [sushiandrobots/sassnews.com#13]
Super easy to use Sass mixins to establish a typographic system with modular scale and vertical rhythm. Based on the [Gridlover app](http://www.gridlover.net/try).
- Repo: https://github.com/hiulit/Sassy-Gridlover
- Docs: http://hiulit.github.io/Sassy-Gridlover/sassdoc/

Hope you like the project!

P.S. Congratulations on the best newsletter about Sass related stuff ;)

**Comment by jina** [comment]
Was sent out in Sass News #82. Thanks!
