### ISSUE TITLE
Fault: Default CSS settings as Silent Sass Class

### ISSUE THREAD

**Issue by jpdevries** [sushiandrobots/sassnews.com#2]
Thanks for taking over Sass News.

I thought I'd share a silent Sass library I just published that others might find helpful. It's called 'Fault' and it provides default CSS settings as silent Sass classes.
https://github.com/jpdevries/fault

### Why?
CSS collisions cramping your style? Ever wish you could just set the properties for a CSS element back to the browser defaults? Now you can!

Somewhat related, I've published a Thinkful lesson on Silencing your CSS Footprint with Silent Classes that focuses on how to use them to keep your payload down.
https://www.thinkful.com/projects/silence-your-css-footprint-with-sass-silent-classes-457/#focus

**Comment by jina** [comment]
Will be in the next issue going out tonight. Thanks!
