### ISSUE TITLE
A couple of new plugins for include-media

### ISSUE THREAD

**Issue by jackmcpickle** [sushiandrobots/sassnews.com#4]
A few plugins for include-media that I wrote to help on our team.

An include-media plugin for spreading css properties over breakpoints - https://github.com/jackmcpickle/include-media-spread

A simple yet flexible class naming structure on top of a flexbox based grid - https://github.com/jackmcpickle/flex_e_ble

**Comment by jina** [comment]
Will be in the next issue going out tonight. Thanks!
