### ISSUE TITLE
CSS Dev Conf 2016 Call for Speakers now open

### ISSUE THREAD

**Issue by teleject** [sushiandrobots/sassnews.com#5]
Call for Speakers is now open for CSS Dev Conf 2016 The Alamo in San Antonio, TX.

http://lanyrd.com/2016/cssdevconf/calls/qdypm/

**Comment by jina** [comment]
Hi @teleject. My apologies for not getting the issue out soon enough to include this one. I'll mention your conference in upcoming events though. :)
